export declare function isFunction(val: unknown): val is (...args: unknown[]) => unknown;
export declare function isArray<T>(val: unknown): val is T[];
export declare function isDate(val: unknown): val is Date;
export declare function isString(val: unknown): val is string;
export declare function isBoolean(val: unknown): val is boolean;
export declare function isNumber(val: unknown): val is number;
export declare function isRegExp(val: unknown): val is RegExp;
export declare function isObject<T>(val: unknown): val is Record<string, T>;
export declare function isFormData(val: unknown): val is FormData;
export declare function isUndefined(val: unknown): val is undefined;
export declare function isNull(val: unknown): val is null;
export declare function isDef(val: unknown): boolean;
export declare function objectKeys<T, K extends keyof T>(object: T): K[];
